### PR TITLE
Added regenerateToken Endpoint

### PR DESCRIPTION
**Pull request by user5423**
Added regenerateToken Endpoint

### CODE REVIEW

**Comment by user5423** [comment]
This also contains incomplete boilerplate of EmailRespond integration, that I will continue to work on this branch. So make sure not to delete

**Review by zshepherd01 — CHANGES_REQUESTED** [review]
A couple of issues with this:

1. The OAS document goes out of spec again. `description` and `$ref` should not be used at the same level, instead the description should be moved into the referenced schema
2. You note that 401-type responses are instead 400, but not why this is the case
3. I don't understand why the DataValidate component is used to validate the authorization header here, when AuthenticationHandler does that job on every other request
4. In the test file, you use `expect(response.headers['Authorization']).toEqual(undefined);`, why not just `expect(response.headers).not.toHaveProperty('Authorization');`?
5. Also in the test file, you `expect(decodedToken['userID'] = payload['userID']);`. This is the assignment operator, not comparison, so this will always be true. Instead, you should probably use `expect(thing).toBe(otherthing);`

**Comment by user5423** [comment]
Resolving issues:
1. I provided no modifications to the oas document definitions as you mentioned that you had finalized these (I have since modified these)
2. See the first point
3. Following the structure of the loginPipleine that was previously created - there's some redundancy here, but I plan on removing all redundancy down the line after restructuring the security-related classes/methods (this will be ensured when all 4 remaining security endpoints (as seen on trello cards) is dealt with) - I've raised issue #69 for this
4. Good point (I've opened #70 to go over my old tests)
5. Good bug catch

**Comment by zshepherd01** [comment]
Moved the "change the response code to 201" thing into the response schema, since that's what it's for. Also modified the status code conditions to be more explicit

**Pull request merged**
